### PR TITLE
filters by tag

### PR DESCRIPTION
**Pull request by AlexanderPavlenko**

### CODE REVIEW

**Comment by PrivateGER** [comment]
I will need a little more explanation on this. What does this do?

**Comment by AlexanderPavlenko** [comment]
Current version downloads all the posts regardless of what's visible on the page.
This change allows to download only media with the same tag as selected in the browser.

**Comment by PrivateGER** [comment]
Ah, okay. Could you add this information to the message shown in the console window as well?

**Comment by AlexanderPavlenko** [comment]
> Could you add this information to the message shown in the console window as well?

Done

**Comment by PrivateGER** [comment]
Thanks :)

**Pull request merged**
